import type { LoadedScenario } from './types';

export const SEED_FIRST_CONTACT_SCENARIO: LoadedScenario = {
  scenario: {
    id: 'scen-first-contact',
    slug: 'first-contact-meeting-someone',
    language: 'en',
    level: 'A0',
    title: 'Primeiro contato: conhecer alguém',
    description: 'Aprenda a cumprimentar alguém, dizer seu nome e responder como você está.',
    contextPt: 'Você encontrou Alex no saguão do hotel.',
    status: 'published',
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    steps: [],
  },
  characters: [
    {
      id: 'char-alex',
      scenarioId: 'scen-first-contact',
      name: 'Alex',
      role: 'interlocutor',
      avatarKey: null,
      voiceKey: null,
    },
  ],
  steps: [
    {
      id: 'step-1',
      sequence: 1,
      stepType: 'context',
      completionRule: 'single_accept',
      speakerCharacterId: null,
      promptEn: null,
      supportPt: 'Você encontrou Alex no saguão do hotel.',
      targetPhrase: null,
      hintLevel1: 'Observe a situação.',
      hintLevel2: 'Quando estiver pronto, continue.',
      audioText: null,
    },
    {
      id: 'step-2',
      sequence: 2,
      stepType: 'listen',
      completionRule: 'single_accept',
      speakerCharacterId: 'char-alex',
      promptEn: 'Hello!',
      supportPt: null,
      targetPhrase: null,
      hintLevel1: 'Ouça a saudação de Alex.',
      hintLevel2: 'Ouça novamente e preste atenção à palavra.',
      audioText: 'Hello!',
    },
    {
      id: 'step-3',
      sequence: 3,
      stepType: 'repeat',
      completionRule: 'single_accept',
      speakerCharacterId: 'char-alex',
      promptEn: 'Hello!',
      supportPt: 'Repita a saudação de Alex.',
      targetPhrase: 'Hello!',
      hintLevel1: 'Diga a mesma saudação.',
      hintLevel2: 'Use uma única palavra: Hello.',
      audioText: 'Hello!',
      expectedResponses: [
        {
          id: 'exp-3-1',
          responseText: 'Hello!',
          normalizedText: 'hello',
          matchType: 'normalized',
          isPrimary: true,
        },
      ],
    },
    {
      id: 'step-4',
      sequence: 4,
      stepType: 'choice',
      completionRule: 'choice_correct',
      speakerCharacterId: null,
      promptEn: 'Alex said hello.',
      supportPt: 'Alex cumprimentou você.',
      targetPhrase: 'Alex said hello.',
      hintLevel1: 'Escolha o significado da situação.',
      hintLevel2: 'Pense no que Alex disse no passo anterior.',
      audioText: null,
      expectedResponses: [
        {
          id: 'exp-4-1',
          responseText: 'Alex said hello.',
          normalizedText: 'alex said hello',
          matchType: 'exact',
          isPrimary: true,
        },
        {
          id: 'exp-4-2',
          responseText: 'Alex asked your name.',
          normalizedText: 'alex asked your name',
          matchType: 'exact',
          isPrimary: false,
        },
        {
          id: 'exp-4-3',
          responseText: 'Alex said goodbye.',
          normalizedText: 'alex said goodbye',
          matchType: 'exact',
          isPrimary: false,
        },
      ],
    },
    {
      id: 'step-5',
      sequence: 5,
      stepType: 'listen',
      completionRule: 'single_accept',
      speakerCharacterId: 'char-alex',
      promptEn: "What's your name?",
      supportPt: null,
      targetPhrase: null,
      hintLevel1: 'Ouça a pergunta de Alex.',
      hintLevel2: 'Ouça novamente e identifique a pergunta sobre seu nome.',
      audioText: "What's your name?",
    },
    {
      id: 'step-6',
      sequence: 6,
      stepType: 'guided_speak',
      completionRule: 'all_required_terms',
      speakerCharacterId: null,
      promptEn: 'My name is ____.',
      supportPt: 'Complete a frase com seu nome.',
      targetPhrase: 'My name is [your name].',
      hintLevel1: 'Comece com: My name is.',
      hintLevel2: 'Diga: My name is e complete com seu nome.',
      audioText: 'My name is',
      requiredTerms: ['my', 'name', 'is'],
      expectedResponses: [
        {
          id: 'exp-6-1',
          responseText: 'My name is [your name].',
          normalizedText: 'my name is',
          matchType: 'contains_required_terms',
          isPrimary: true,
        },
      ],
    },
    {
      id: 'step-7',
      sequence: 7,
      stepType: 'free_speak',
      completionRule: 'all_required_terms',
      speakerCharacterId: null,
      promptEn: 'Answer Alex with your own name.',
      supportPt: 'Responda usando seu próprio nome.',
      targetPhrase: 'My name is [your name].',
      hintLevel1: 'Use as palavras: My name is.',
      hintLevel2: 'Diga My name is e depois o seu nome.',
      audioText: 'My name is [your name].',
      requiredTerms: ['my', 'name', 'is'],
      expectedResponses: [
        {
          id: 'exp-7-1',
          responseText: 'My name is [your name].',
          normalizedText: 'my name is',
          matchType: 'contains_required_terms',
          isPrimary: true,
        },
      ],
    },
    {
      id: 'step-8',
      sequence: 8,
      stepType: 'listen',
      completionRule: 'single_accept',
      speakerCharacterId: 'char-alex',
      promptEn: 'How are you?',
      supportPt: null,
      targetPhrase: null,
      hintLevel1: 'Ouça como Alex pergunta como você está.',
      hintLevel2: 'Ouça novamente a pergunta de Alex.',
      audioText: 'How are you?',
    },
    {
      id: 'step-9',
      sequence: 9,
      stepType: 'guided_speak',
      completionRule: 'single_accept',
      speakerCharacterId: null,
      promptEn: 'I’m good, thank you.',
      supportPt: 'Use uma resposta curta e educada.',
      targetPhrase: 'I’m good, thank you.',
      hintLevel1: 'Comece com: I’m good.',
      hintLevel2: 'Complete com: thank you ou thanks.',
      audioText: 'I’m good, thank you.',
      expectedResponses: [
        {
          id: 'exp-9-1',
          responseText: 'I’m good, thank you.',
          normalizedText: 'im good thank you',
          matchType: 'normalized',
          isPrimary: true,
        },
        {
          id: 'exp-9-2',
          responseText: 'I’m good, thanks.',
          normalizedText: 'im good thanks',
          matchType: 'accepted_variant',
          isPrimary: false,
        },
        {
          id: 'exp-9-3',
          responseText: 'I am good, thank you.',
          normalizedText: 'i am good thank you',
          matchType: 'accepted_variant',
          isPrimary: false,
        },
        {
          id: 'exp-9-4',
          responseText: 'I am good, thanks.',
          normalizedText: 'i am good thanks',
          matchType: 'accepted_variant',
          isPrimary: false,
        },
      ],
    },
    {
      id: 'step-10',
      sequence: 10,
      stepType: 'recap',
      completionRule: 'single_accept',
      speakerCharacterId: 'char-alex',
      promptEn: "Alex: Hello!\nYou: Hello!\nAlex: What's your name?\nYou: My name is [name].",
      supportPt: null,
      targetPhrase: null,
      hintLevel1: 'Reply after each line.',
      hintLevel2: 'Use the phrases from the previous steps.',
      audioText: "Hello! What's your name?",
    },
  ],
};

SEED_FIRST_CONTACT_SCENARIO.scenario.steps = SEED_FIRST_CONTACT_SCENARIO.steps;
