/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionsAirportRouteImport } from './routes/missions.airport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsAirportRoute = MissionsAirportRouteImport.update({
  id: '/missions/airport',
  path: '/missions/airport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/missions/airport': typeof MissionsAirportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/missions/airport': typeof MissionsAirportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/missions/airport': typeof MissionsAirportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/missions/airport'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/missions/airport'
  id: '__root__' | '/' | '/missions/airport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MissionsAirportRoute: typeof MissionsAirportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/airport': {
      id: '/missions/airport'
      path: '/missions/airport'
      fullPath: '/missions/airport'
      preLoaderRoute: typeof MissionsAirportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MissionsAirportRoute: MissionsAirportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
